#application.yml
spring:
  datasource:
    url: jdbc:h2:file:/home/ubuntu/app/data/driving_analysis
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 테스트용
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.H2Dialect  # MySQL이 아닌 H2 방언 사용
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  websocket:
    max-text-message-size: 50MB
    max-binary-message-size: 50MB

jwt:
  secret: yourSecretKeyHereShouldBeLongEnoughToBeSecure
  expiration: 86400000  # 24시간

logging:
  level:
#    org.hibernate.SQL: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

# AI 서버 연결 설정
ai:
  server:
    host: 0.tcp.jp.ngrok.io
    port: 12608
    timeout: 30  # 요청 타임아웃(초)
    retry:
      max: 2     # 최대 재시도 횟수
